yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Group


# Главная страница
def index(request):
    """Главная страница проекта yatube."""

    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, '../templates/posts/index.html', context)


def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, '../templates/posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png"
          href="{% static '/img/fav/favicon.ico' %}">
    <link rel="icon" href="{% static '/img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180"
          href="{% static '/img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static '/img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static '/img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block title %}
        Yatube - проект
    {% endblock %}
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %} 
    </header>
    <main>
      {% block content %}
        Нет контента :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
<p>©Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<div class="container">
  <a class="navbar-brand" href="{% url 'posts:index' %}">
    <img src="{% static 'img/logo.png' %}" width="30"
         height="30" class="d-inline-block align-top" alt="">
    <span style="color:red">Ya</span>tube
  </a>
</div>

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html --> 
{% extends 'base.html' %}
{% block title %}
  <title>
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
  </title>
{% endblock %}

{% block content %}
  <div class="container py-5">
     <h1>Записи сообщества: {{ group.title }}</h1>
     <p>{{ group.description }}</p>
      <article>
      {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ posts.text }}</p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      </article>
  </div>  
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% block title %}<title>Последние обновления на сайте</title>{% endblock %}
{% block content %}
<div class="container py-5">
  <article>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <ul>
      <li>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы</a>
        {% else %}
          <a href="">
            все записи группы</a>
        {% endif %}
      </li>
      </ul>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
</div>
{% endblock %}